#!/usr/bin/env node
/**
 * build-data.js
 *
 * Reads all JSON files from /resources/ directory (produced by Decap CMS),
 * and generates /assets/js/data.js consumed by index.html.
 *
 * Supports bilingual fields:
 *   title_zh / title_en  →  title (per active lang, falls back to title)
 *   desc_zh  / desc_en   →  desc  (per active lang, falls back to desc)
 *   title / desc (legacy) →  used as fallback
 */

const fs   = require('fs');
const path = require('path');

const RESOURCES_DIR = path.join(__dirname, '..', 'resources');
const OUTPUT_FILE    = path.join(__dirname, '..', 'assets', 'js', 'data.js');

function build() {
  if (!fs.existsSync(RESOURCES_DIR)) {
    console.warn('⚠  resources/ directory not found — creating empty data.js');
    writeDataJs([]);
    return;
  }

  const files = fs.readdirSync(RESOURCES_DIR)
    .filter(f => f.endsWith('.json'))
    .sort();

  const resources = files.map((file, i) => {
    const raw  = fs.readFileSync(path.join(RESOURCES_DIR, file), 'utf8');
    const data = JSON.parse(raw);

    // Bilingual support: fall back gracefully
    const title_zh = data.title_zh || data.title || '';
    const title_en = data.title_en || data.title || '';
    const desc_zh  = data.desc_zh  || data.desc || '';
    const desc_en  = data.desc_en  || data.desc || '';

    return {
      id:       i + 1,
      title_zh,
      title_en,
      desc_zh,
      desc_en,
      // Legacy flat fields for old resources — kept for backward compat
      title: data.title || title_zh || title_en || '',
      desc:  data.desc  || desc_zh  || desc_en  || '',
      url:      data.url      || '#',
      category: data.category || 'other',
      icon:     data.icon     || '🔗',
      tags:     Array.isArray(data.tags) ? data.tags : (data.tags ? [data.tags] : []),
      featured: !!data.featured
    };
  });

  writeDataJs(resources);
  console.log(`✓ Built data.js with ${resources.length} resource(s) from resources/*.json`);
}

function writeDataJs(resources) {
  // We export both the flat array (legacy) and a helper
  const json = JSON.stringify(resources, null, 2);
  const js   = [
    '// Auto-generated by build-data.js — DO NOT EDIT',
    '',
    `const RESOURCES = ${json};`,
    '',
    '/**',
    ' * Get title/desc for a resource in the given language.',
    ' * @param {object} r  - resource object',
    ' * @param {string} lang - "zh" | "en"',
    ' * @returns {{ title: string, desc: string }}',
    ' */',
    'function rText(r, lang) {',
    '  if (lang === "zh") {',
    '    return {',
    '      title: r.title_zh || r.title || "",',
    '      desc:  r.desc_zh  || r.desc  || ""',
    '    };',
    '  }',
    '  return {',
    '    title: r.title_en || r.title || "",',
    '    desc:  r.desc_en  || r.desc  || ""',
    '  };',
    '}',
  ].join('\n');

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, js, 'utf8');
}

build();